trigger:
- main

pool:
  name: local-agnet  # Make sure this matches your self-hosted agent pool

steps:
- script: echo "Hello from Azure Pipeline!"
  displayName: "Greeting"

- script: |
    echo "Checking content of index.html"
    type index.html  # 'type' is the Windows equivalent of 'cat'
  displayName: "Show index.html content"
