
trigger:
- master

pool:
  name: local-agnet  

steps:
- script: echo "Hello from Azure Pipeline!"
  displayName: "Greeting"

- script: |
    echo "Checking content of index.html"
    cat index.html
  displayName: "Show index.html content"
